#     _   _   _          _      _   _   ___ 
#    | \ | | (_)   ___  | | __ | | | | |_ _|
#    |  \| | | |  / __| | |/ / | | | |  | | 
#    | |\  | | | | (__  |   <  | |_| |  | | 
#    |_| \_| |_|  \___| |_|\_\  \___/  |___|
#          by fernanACM
#A simple menu to change your nickname. All messages and certain options can be changed, 
#any bugs that come up please report on github: https://github.com/fernanACM
#======================================================================================
                    #NickUI settings - Messages
#Prefix message
Prefix: "§l§7[§bNickUI§7]§8»§r "
#Add random nicknames with this example:
# Random-nicks:
#   - Friend
#   - ACM
#   - Cars
Random-nicks:
  - ACM
  - Player9920
  - Gamer90
  - Jonatan
  - Jona
  - AbelGod
  - Naruto
  - SIPE
  - CELAR
  - GO3992
#Write here nicknames that you do not like or are risque
#Add the banned nicknames with the following example:
#Not-allow-custom-nicks:
#  - Shit
#  - Fuck
#  - Bitch
Not-allow-custom-nicks:
  - ServerTeam
  - HateYou
  - PocketMine-MP
  - Gay
  - Shit
  - Fuck
  - Bitch
  - Owner
  - Admin
  - "@here"
  - Server
#Forbidden nickname message  
Not-allowed-nick: "§cThis Nick is not allowed."
#Options disable message
Disabled: "§cThis option has been disabled."
#==========================================================
#               FORM MESSAGES

#MESSAGES - NICKUI
Nick-Existen: "§l§cSorry!§r§7 But you cannot change your name, because your name is already normal."
Nick-Normal: "§aYour name is now normal."
#Use "{NICK}" to see nickname
Nick-New: "§aYour name is now:§e {NICK}"

#FORM MESSAGE - NICKUI
Nick-Content: "§7Change your nickname discreetly\n§7Your nickname is:§a "
Content-Normal: "§7Change your nickname discreetly\n\n§7You don't have §c§lany§r§7 nickname."

Button-Nick: "§l§3Create a new nickname\n§r§0click to open"
Button-Random: "§l§9Random nickname\n§r§0click to open"
Button-Reset: "§l§4Remove nickname\n§r§0click to open"
#Button-HideNick: "§l§6Hide your name\n§r§0click to open"
Button-Exit: "§c§lEXIT\n§r§0close menu"

Input: "§7Here you can type your custom nickname:"
#=================================================
#               COMING SOON
#MESSAGES - HIDEUI
#Hide-Enable: "§7Your name has§a faded"
#Hide-Disable: "§7Your name is now§c visible"

#FORM MESSAGE - HIDEUI
#Button-Enable: "§l§2Enable\n§r§0hide name"
#Button-Disable: "§l§4Disable\n§r§0display name"
#Button-Exit: "§c§lEXIT\n§r§0close menu"
